"""Unit tests for DistributedBackend in drigs.execution.distributed."""

import os
import time
import pytest
import tempfile
from pathlib import Path

from drigs.core.interfaces import ExecutionBackend
from drigs.core.models import (
    Job,
    JobStatus,
    ResourceAllocation,
    ResourceRequirements,
    WorkloadDistributionConfig,
    WorkloadExecutionConfig,
    WorkloadSpec,
)
from drigs.execution.distributed import DistributedBackend, find_free_port


def test_distributed_backend_protocol():
    backend = DistributedBackend()
    assert isinstance(backend, ExecutionBackend)


def test_find_free_port():
    port = find_free_port()
    assert isinstance(port, int)
    assert 1024 <= port <= 65535


def test_distributed_backend_multi_rank_launch():
    with tempfile.TemporaryDirectory() as tmpdir:
        out_file_0 = Path(tmpdir) / "rank_0.txt"
        out_file_1 = Path(tmpdir) / "rank_1.txt"

        script_path = Path(tmpdir) / "worker_script.py"
        script_path.write_text(
            f"""import os, time
from pathlib import Path
rank = os.environ.get('RANK')
ws = os.environ.get('WORLD_SIZE')
addr = os.environ.get('MASTER_ADDR')
port = os.environ.get('MASTER_PORT')
out_path = Path('{tmpdir}') / f"rank_{{rank}}.txt"
with open(out_path, 'w') as f:
    f.write(f"rank={{rank}},ws={{ws}},addr={{addr}},port={{port}}")
time.sleep(0.1)
print(f"Rank {{rank}} finished successfully")
""",
            encoding="utf-8",
        )

        spec = WorkloadSpec(
            name="dist-test",
            resources=ResourceRequirements(cpus=2),
            execution=WorkloadExecutionConfig(
                entrypoint=["python3", str(script_path)]
            ),
            distribution=WorkloadDistributionConfig(
                mode="distributed",
                world_size=2,
                master_addr="127.0.0.1",
            ),
        )
        job = Job(name="dist-job", spec=spec)
        alloc = ResourceAllocation(
            job_id=job.id,
            worker_id="worker-0",
            assigned_device_ids=["gpu-0", "gpu-1"],
            assigned_cpu_cores=[0, 1],
            memory_bytes=8 * 1024**3,
        )

        backend = DistributedBackend(log_dir=tmpdir)
        handle = backend.launch(job, alloc)

        assert handle.backend_type == "DISTRIBUTED"
        assert handle.metadata["world_size"] == 2

        # Poll status until completed
        start_time = time.time()
        status = JobStatus.RUNNING
        while time.time() - start_time < 5.0:
            status = backend.get_status(handle)
            if status in (JobStatus.COMPLETED, JobStatus.FAILED):
                break
            time.sleep(0.1)

        assert status == JobStatus.COMPLETED

        # Verify output files generated by each rank
        assert out_file_0.exists()
        assert out_file_1.exists()

        content0 = out_file_0.read_text(encoding="utf-8")
        assert "rank=0" in content0
        assert "ws=2" in content0

        content1 = out_file_1.read_text(encoding="utf-8")
        assert "rank=1" in content1
        assert "ws=2" in content1

        # Check logs
        logs = backend.read_logs(handle)
        assert "[Rank 0]" in logs
        assert "[Rank 1]" in logs


def test_distributed_backend_stop():
    with tempfile.TemporaryDirectory() as tmpdir:
        python_cmd = "import time; time.sleep(30)"
        spec = WorkloadSpec(
            name="long-dist",
            resources=ResourceRequirements(cpus=2),
            execution=WorkloadExecutionConfig(
                entrypoint=["python3", "-c", python_cmd]
            ),
            distribution=WorkloadDistributionConfig(world_size=2),
        )
        job = Job(name="stop-job", spec=spec)
        alloc = ResourceAllocation(
            job_id=job.id,
            worker_id="worker-0",
            assigned_device_ids=["gpu-0", "gpu-1"],
            assigned_cpu_cores=[0, 1],
        )

        backend = DistributedBackend(log_dir=tmpdir)
        handle = backend.launch(job, alloc)
        assert backend.get_status(handle) == JobStatus.RUNNING

        stopped = backend.stop(handle)
        assert stopped is True
        assert backend.get_status(handle) == JobStatus.CANCELLED
